openapi: 3.0.1
info:
  title: Tarifas
  description: Aplicação de tarifas sobre os produtos Bankly. 
  version: '1.0'
servers:
  - url: https://api-mtls.sandbox.bankly.com.br
paths:
  /fee:
    post:
      tags:
        - Criação 
      summary: Criação de tarifa
      description: |
        <div class="bkly-ref-description">
          <p>Crie tarifas para as transações realizadas com os produtos que você oferece aos seus clientes.</p> 
          <span class="bkly-ref-small-beta-tag">beta</span> 
          <span class="bkly-ref-scope-tag">scope: fee.create</span>
        </div>  
        
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/Authorization'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/X-Correlation-Id'
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createFeeCommand'
      responses:
        '202':
          description: Recurso criado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFeeCommand'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
      security:
        - Bearer: []

  /fee/branches/{bankBranch}/accounts/{accountNumber}/authenticationcode/{authenticationCode}:
      get:
        tags:
        - Consulta 
        summary: Consulta de tarifas
        description: |
          <div class="bkly-ref-description">
            <p>Realize a consulta das tarifas aplicadas aos produtos de uma determinada conta.</p> 
            <span class="bkly-ref-small-beta-tag">beta</span> 
            <span class="bkly-ref-scope-tag">scope: fee.read</span>
          </div>  
        parameters:
          - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
          - $ref: 'http://localhost:3320/commons/components#/components/parameters/Authorization'
          - $ref: 'http://localhost:3320/commons/components#/components/parameters/X-Correlation-Id'
          - name: authenticationCode
            in: path
            required: true
            description: Valor retornado no response de criação da tarifa.
            schema:
              type: string
              format: uuid
          - name: bankBranch
            in: path
            required: true
            schema:
              type: string
          - name: accountNumber
            in: path
            required: true
            schema:
              type: string

        responses:
          '200':
            description: Recurso encontrado. 
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/responseFeeCommand'
          '400':
            $ref: 'http://localhost:3320/commons/components#/components/responses/400'
          '403':
            $ref: 'http://localhost:3320/commons/components#/components/responses/403'
              
        security:
          - Bearer: []

components:
  schemas:
    account:
      type: object
      required:
        - branch
        - number
      properties:
        branch:
          type: string
          nullable: true
        number:
          type: string
          nullable: true
      additionalProperties: false

    accountSimple:
      type: string

    createFeeCommand:
      type: object
      required:
        - transactionId
        - transactionType
        - amount
        - description
        - recipient
        - payer
        - createdAt
        - updatedAt
      properties:
        transactionId:
          type: string
          format: uuid
          nullable: true 
          description: Informe um GUID. Esse campo não obrigatório para cobranças do tipo (transactionType) OTHER.
        transactionType:
          $ref: '#/components/schemas/transactionType'
        amount:
          type: number
          format: double
          description: Valor da tarifa em BRL. 
        description:
          type: string
          nullable: true
          description: Descrição da tarifa.
        recipient:
          $ref: '#/components/schemas/recipient'
        payer:
          $ref: '#/components/schemas/payer'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: Data de atualização da tarifa (no dia da criação da tarifa, esse campo envia o mesmo valor que o campo <code>createdAt</code>).
      additionalProperties: false

    payer:
      type: object
      required:
        - account
        - documentNumber
      properties:
        account:
          $ref: '#/components/schemas/account'
        documentNumber:
          type: string
          nullable: true
      additionalProperties: false
    
    payerResponse:
      type: object
      properties:
        branch:
         type: string
        account:
          type: string      
      additionalProperties: false

    recipient:
      type: object
      required:
        - account
        - documentNumber
      properties:
        account:
          $ref: '#/components/schemas/account'
        documentNumber:
          type: string
          nullable: true
      additionalProperties: false

    responseFeeCommand:
      type: object
      properties:
        authenticationCode: 
          type: string
          description: Código identificador.
        transactionType:
          $ref: '#/components/schemas/transactionType'        
        amount:
          type: number
          format: double
          description: Valor da tarifa em BRL.         
        status:
          type: string
          enum:
            - CREATED
            - CANCELED
            - DONE
            - UNDONE
        description:
          type: string
          nullable: true
          description: Descrição da tarifa.     
        accountNumber: 
          $ref: '#/components/schemas/accountSimple'
        payer:
          $ref: '#/components/schemas/payerResponse'

      
        
    transactionType:
      enum:
        - TED
        - OTHER
      type: string
    
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer.
      scheme: bearer
      
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
