openapi: 3.0.1
info:
  version: 1.0.0
  title: '[Nome da API. Ex: Gestão de Contas, Gestão de Cartões]'
  description: |
    [Breve descrição da API.]
servers:
  - url: 'https://api.sandbox.bankly.com.br'

paths: 
  /cards/credits/customers:
    post:
      tags:
        - Criar nova análise de crédito
      summary: Análise de crédito
      description: |
        <div class="bkly-ref-description">
          <p>Cria uma nova análise de crédito para o cliente.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span>
        </div>
      operationId: cardCreateVirtualCard
      responses:
        "401":
          description: Sem autorização para realizar a solicitação.

security:
  - Bearer: []

components: {}
  
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl