openapi: 3.0.3

info:
  title: Componentes comuns para todas as APIs.
  version: '1.0'

paths: {}

components:
  
  parameters:

    ApiVersion:
      name: api-version
      in: header
      description: |
        Versão da API.
        _Atualmente estamos na **1.0**._
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: 1

    ApiVersion2:
      name: api-version
      in: header
      description: |
        Versão da API.
        _Utilize este endpoint na **versão 2.0**._
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: 2

    Authorization: 
      name: Authorization
      in: header 
      required: true
      style: simple
      explode: false
      schema:
        type : string

    IdempotencyKey:
      name: Idempotency-Key
      in: header
      description: Chave de idempotêcia para a requisição (UUID v4).
      required: false
      style: simple
      explode: false
      schema:
        type: string

    CustomerDocument:
      name: documentNumber
      in: path
      description: Número do documento CPF do cliente pessoa física ou representante legal da empresa. Informe somente os números.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/CustomerDocument'

    BusinessDocument:
      name: documentNumber
      in: path
      description: Número do documento CNPJ da empresa. Informe somente os números.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/BusinessDocument'

    AccountNumber:
      name: accountNumber
      in: path
      description: |
        Número da conta.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/AccountNumber'

    BankBranch:
      name: branch
      in: path
      description: |
        Agência bancária.
        _Default: **0001**._
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/BankBranch'

    BankBranchQuery:
      name: branch
      in: query
      description: |
        Agência bancária.
        _Default: **0001**._
      required: true
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/BankBranch'

    ResultLevel:
      name: resultLevel
      in: query
      description: |
        Tipo de retorno da API.
      required: false
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/ResultLevel'

    AccountNumberQuery:
      name: account
      in: query
      description: |
        Número da conta de pagamento.
      required: true
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/AccountNumber'
    
    X-bkly-pix-user-id:
      name: x-bkly-pix-user-id
      in: header
      description: Número do documento do usuário que está fazendo a requisição. Insira apenas números, sem formatação. 
      required: true
      schema:
        type: string

    X-Company-Key:
      name: x-company-key
      in: header
      description: Chave que identifica o parceiro dentro do Bankly.
      required: true
      schema: 
        type: string

    X-Correlation-Id:  
      name: x-correlation-id
      in: header 
      description: Informe um GUID v4. A cada requisição, deve-se gerar um novo GUID.
      required: true
      schema:
        $ref: '#/components/schemas/X-Correlation-Id'

    Bankly-Correlation-Id:  
      name: bankly-correlation-id
      in: header 
      description: Informe um GUID v4. A cada requisição, deve-se gerar um novo GUID.
      required: true
      schema:
        $ref: '#/components/schemas/X-Correlation-Id'

    X-Idempotency-Key:
      name: x-idempotency-key
      in: header
      description: Chave de idempotência para a requisição (UUID v4).
      required: true
      style: simple
      explode: false
      schema:
        type: string

    Bankly-Idempotency-Key:
      name: bankly-idempotency-key
      in: header
      description: Chave de idempotência para a requisição (UUID v4).
      required: true
      style: simple
      explode: false
      schema:
        type: string
  
  schemas:

    Error:
      type: object
      properties:
        code:
          description: Código do erro.
          type: string
          nullable: true
        propertyName:
          description: Parâmetro ou propriedade com problema. Somente será retornado quando o erro for de sintaxe (Bad Request). 
          type: string
          nullable: true
        message:
          description: Lista de descrições do problema encontrado. 
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false

    ErrorResponse:
      description: Detalhes do erro identificado.
      type: object
      properties:
        errors:
          description: Lista de erros identificados. Trate-os antes de tentar novamente.
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Error'
        reference:
          type: string
      additionalProperties: false

    CustomerDocument:
      description: Número do documento CPF do cliente do cliente pessoal ou representante legal.
      type: string
      maxLength: 11
      minLength: 11

    BusinessDocument:
      description: Número do documento CNPJ da empresa.
      type: string
      maxLength: 14
      minLength: 14
      pattern: "^[0-9]*$"
    
    AccountNumber:
      description: Número da conta de pagamento.
      type: string
      minLength: 3
      maxLength: 13

    BankBranch:      
      type: string
      minLength: 4
      maxLength: 4
      description: |
        Agência bancária.
        _Default: **0001**._    
    
    Address:
      description: Endereço do cliente, da empresa ou de seu representante legal.
      required:
        - zipCode
        - addressLine
        - buildingNumber
        - neighborhood
        - city
        - state
        - country
      type: object
      properties:
        zipCode:
          minLength: 9
          maxLength: 9
          type: string
          description: |
            O CEP correspondente ao endereço. 
            **_Informe somente os números._**
        addressLine:
          maxLength: 256
          minLength: 1
          type: string
          description: |
            Logradouro (Nome da rua, avenida, etc). 
            **_Caso não exista, preencha S/N._**
        buildingNumber:
          maxLength: 10
          minLength: 1
          type: string
          description: Número da residência.
        complement:
          maxLength: 256
          type: string
          description: |
            Complemento do endereço.
            _Exemplo: Apto 123, Casa B, etc._
          nullable: true
        neighborhood:
          maxLength: 256
          minLength: 1
          type: string
          description: Nome do bairro ou distrito.
        city:
          maxLength: 256
          minLength: 1
          type: string
          description: Nome da cidade.
        state:
          description: |
            Sigla do estado brasileiro conforme a ISO 3166-2:BR.
            _AC, AL, AP, AM, BA, CE, DF, ES, GO, MA, MT, MS, MG, PA, PB, PR, PE, PI, RJ, RN, RS, RO, RR, SC, SP, SE, TO_
          $ref: '#/components/schemas/State'
        country:
          maxLength: 2
          minLength: 2
          type: string
          default: BR
          description: |
            Sigla do país (Brasil) conforme a ISO 3166. 
            _Exemplo: BR._
      additionalProperties: false

    Phone:
      required:
        - countryCode
        - number
      type: object
      properties:
        countryCode:
          maxLength: 3
          minLength: 2
          type: string
          description: |
            Código DDI do país. 
            _Por enquanto é permitido apenas **55** ou **+55** (Brasil)._
        number:
          minLength: 11
          maxLength: 11
          type: string
          description: Número de telefone incluindo DDD.
      additionalProperties: false

    ResultLevel:
      type: string
      description: |
        Tipo de retorno da API.
        _(BASIC, DETAILED)_
      default: BASIC
      enum:
        - BASIC
        - DETAILED

    State:
      type: string
      description: Sigla do estado brasileiro conforme a ISO 3166-2:BR.
      enum:
        - AP
        - AC
        - AL
        - AP
        - AM
        - BA
        - CE
        - DF
        - ES
        - GO
        - MA
        - MT
        - MS
        - MG
        - PA
        - PB
        - PR
        - PE
        - PI
        - RJ
        - RN
        - RS
        - RO
        - RR
        - SC
        - SP
        - SE
        - TO
    
    X-Correlation-Id:
      type: string
      description: Informe um GUID v4. A cada requisição, deve-se gerar um novo GUID.

    
  headers:
    CorrelationId:
      description: Id correlação da operação requisitada.
      style: simple
      explode: false
      schema:
        type: string

    Location:
      description: Localização do recurso recém-criado ou em processamento.
      style: simple
      explode: false
      schema:
        type: string

  responses:
    '202':
      description: A requisição foi aceita e está sendo processada.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
        Location:
          $ref: '#/components/headers/Location'
    
    '204':
      description: A requisição foi aceita e está sendo processada.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
        Location:
          $ref: '#/components/headers/Location'
    
    '400':
      description: Há algum problema com a sua requisição.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/invalidParameterErrorResponse'
    
    '401':
      description: |
        Acesso não autorizado.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'

    '403':
      description: |
        O acesso ao recurso foi negado pelo servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    
    '404':
      description: |
        Recurso não encontrado.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'

    '405':
      description: |
        Recurso acessado com método não suportado.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'

    '406':
      description: A solicitação não foi aceita.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    
    '408':
      description: O servidor não recebeu uma mensagem de solicitação completa dentro do tempo em que estava preparado para aguardar.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'

    '409':
      description: |
        A solicitação conflitou com o estado atual do recurso existente no servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    
    '415':
      description: |
        Formato de payload não suportado.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'

    '422':
      description: |
        A sintaxe da requisição está correta, mas não foi possível processá-la devido a uma regra de negócio.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    
    '429':
      description: |
        A operação foi recusada, pois muitas solicitações foram feitas dentro de um determinado período ou o limite global de requisições concorrentes foi atingido.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'

    '500':
      description: |
        Ocorreu algum erro inexperado em nosso servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/serverErrorResponse'

    '503':
      description: |
        O serviço está temporariamente indisponível.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'

  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer
  
  examples:

    invalidParameterErrorResponse:
      value:
        errors:
          - code: INVALID_PARAMETER
            propertyName: '{{propertyName}}'
            messages:
              - '{{"propertyName" error message}}'
        reference: "link"
      summary: Parametro inválido
  
    serverErrorResponse:
      value:
        errors:
          - code: SOME_ERROR_CODE
            messages:
              - '{{Some error message}}'
        reference: "link"

      summary: Erro no servidor

    errorResponse:
      value:
        errors:
          - code: SOME_ERROR_CODE
            messages:
              - '{{Some error message}}'
        reference: "link"

      summary: Erro comum/específico
