openapi: 3.0.1
info:
  title: Transações bandeiradas com cartões
  description: API para autenticação de transações bandeiradas através do protocolo Flow3DS
  version: '1.0'
servers:
  - url: https://api.sandbox.bankly.com.br
paths:
  /card-network-transactions/simulator/challenge:
    post:
      tags:
        - Autenticação 3DS
      summary: Simulação de criação do desafio (challengeId)
      description:  |
        <div class="bkly-ref-description">
          <p>Teste o fluxo de autenticação 3DS, simulando a criação do challengeId, id da transação gerado para identificar o desafio que deverá ser enviado a seu cliente. </p> 
          <span class="bkly-ref-small-stable-tag">stable</span>
          <span class="bkly-ref-scope-tag">scope: card.network.transactions.3ds.write</span>
        </div>
        [block:callout]
        {
          "type": "info",
          "title": "Importante",
          "body": "Este endpoint funciona apenas em ambiente de sandbox."
        }
        [/block]
      parameters:
        - $ref: "http://localhost:3320/commons/components#/components/parameters/ApiVersion"
        - $ref: "http://localhost:3320/commons/components#/components/parameters/Authorization"
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateChallengeSimulatorCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChallengeSimulatorCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateChallengeSimulatorCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateChallengeSimulatorCommand'
      responses:
        '202':
          description: ChallengeId criado com sucesso.
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
      security:
        - Bearer: [ ]
  /card-network-transactions/authentication/challenge/{challengeId}/confirm:
    patch:
      tags:
        - Autenticação 3DS
      summary: Confirmação do desafio
      description:  |
        <div class="bkly-ref-description">
          <p>Após o seu cliente responder o desafio, utilize este endpoint para confirmar ou não a sua identidade.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: card.network.transactions.3ds.write</span>
        </div>  
      parameters:
        - name: challengeId
          in: path
          required: true
          description: Id recebido via webhook e que foi associado ao desafio enviado ao cliente do parceiro. No caso de sandbox, trata-se do <code>id</code> retornado na simulação de criação do <code>challengeId</code>.
          schema:
            type: string
            nullable: true
        - $ref: "http://localhost:3320/commons/components#/components/parameters/ApiVersion"
        - $ref: "http://localhost:3320/commons/components#/components/parameters/Authorization"
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ConfirmChallengeCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmChallengeCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/ConfirmChallengeCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ConfirmChallengeCommand'
      responses:
        '204':
          description: Desafio confirmado com sucesso.
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '404':
          $ref: 'http://localhost:3320/commons/components#/components/responses/404'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
      security:
        - Bearer: [ ]
components:
  schemas:
    CreateChallengeSimulatorCommand:
      required:
        - amount
        - card
        - merchant
      type: object
      properties:
        card:
          $ref: '#/components/schemas/ChallengeCard'
        deviceChannel:
          $ref: '#/components/schemas/DeviceChannel'
        merchant:
          $ref: '#/components/schemas/ChallengeMerchant'
        amount:
          $ref: '#/components/schemas/ChallengeAmount'
      additionalProperties: false
      
    ConfirmChallengeCommand:
      required:
        - allowTransaction
        - documentNumber
      type: object
      properties:
        allowTransaction:
          type: boolean
        documentNumber:
          minLength: 1
          type: string
      additionalProperties: false
    
    ChallengeCard:
      required:
        - proxy
      type: object
      properties:
        proxy:
          minLength: 1
          type: string
      additionalProperties: false
    
    DeviceChannel:
      enum:
        - APP
        - BROWSER
      type: string
      description: Selecione o canal por meio do qual é realizada a tentativa de compra.
    
    ChallengeMerchant:
      required:
        - name
      type: object
      description: Nome do e-commerce no qual foi realizada a compra.
      properties:
        name:
          minLength: 1
          type: string
      additionalProperties: false
    
    ChallengeAmount:
      required:
       - value
       - currency
      type: object
      properties:
        value:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        currency:
          maxLength: 3
          minLength: 3
          type: string
          description: "Código [ISO 4217](https://pt.wikipedia.org/wiki/ISO_4217) da moeda utilizada. Exemplo: \"986\" para BRL."
      additionalProperties: false
        
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer

x-explorer-enabled: true
x-samples-enabled: true
x-samples-languages:
  - csharp
  - javascript
  - node
  - go
  - java
  - kotlin
  - php
  - python
  - ruby
  - swift
  - cplusplus
  - powershell
  - curl